### ISSUE TITLE
大佬 这个问题我解决不了 也重新拉源码了 node版本也换过

### ISSUE THREAD

**Issue by ligehhh** [zhaojh329/oui#203]
m -f /home/lihh/oui/lede/build_dir/target-x86_64_musl/oui-app-acl-git-2022.321.10303-e567d9c/.built
touch /home/lihh/oui/lede/build_dir/target-x86_64_musl/oui-app-acl-git-2022.321.10303-e567d9c/.built_check
PATH=/usr/local/bin:/usr/bin npm --prefix /home/lihh/oui/lede/build_dir/target-x86_64_musl/oui-app-acl-git-2022.321.10303-e567d9c/htdoc run build

> oui-app@ build /home/lihh/oui/lede/build_dir/target-x86_64_musl/oui-app-acl-git-2022.321.10303-e567d9c/htdoc
> vite build

vite v3.1.6 building for production...
✓ 0 modules transformed.
[vite:vue] Failed to resolve vue/compiler-sfc.
@vitejs/plugin-vue requires vue (>=3.2.25) to be present in the dependency tree.
error during build:
Error: Failed to resolve vue/compiler-sfc.
@vitejs/plugin-vue requires vue (>=3.2.25) to be present in the dependency tree.
    at resolveCompiler (/home/lihh/oui/lede/build_dir/target-x86_64_musl/oui-app-acl-git-2022.321.10303-e567d9c/htdoc/node_modules/@vitejs/plugin-vue/dist/index.cjs:23:11)
    at Object.buildStart (/home/lihh/oui/lede/build_dir/target-x86_64_musl/oui-app-acl-git-2022.321.10303-e567d9c/htdoc/node_modules/@vitejs/plugin-vue/dist/index.cjs:2602:46)
    at file:///home/lihh/oui/lede/build_dir/target-x86_64_musl/oui-app-acl-git-2022.321.10303-e567d9c/htdoc/node_modules/rollup/dist/es/shared/rollup.js:22710:40
    at async Promise.all (index 4)
    at async PluginDriver.hookParallel (file:///home/lihh/oui/lede/build_dir/target-x86_64_musl/oui-app-acl-git-2022.321.10303-e567d9c/htdoc/node_modules/rollup/dist/es/shared/rollup.js:22638:9)
    at async file:///home/lihh/oui/lede/build_dir/target-x86_64_musl/oui-app-acl-git-2022.321.10303-e567d9c/htdoc/node_modules/rollup/dist/es/shared/rollup.js:23688:13
    at async catchUnfinishedHookActions (file:///home/lihh/oui/lede/build_dir/target-x86_64_musl/oui-app-acl-git-2022.321.10303-e567d9c/htdoc/node_modules/rollup/dist/es/shared/rollup.js:23088:20)
    at async rollupInternal (file:///home/lihh/oui/lede/build_dir/target-x86_64_musl/oui-app-acl-git-2022.321.10303-e567d9c/htdoc/node_modules/rollup/dist/es/shared/rollup.js:23686:5)
    at async doBuild (file:///home/lihh/oui/lede/build_dir/target-x86_64_musl/oui-app-acl-git-2022.321.10303-e567d9c/htdoc/node_modules/vite/dist/node/chunks/dep-db16f19c.js:45815:24)
    at async build (file:///home/lihh/oui/lede/build_dir/target-x86_64_musl/oui-app-acl-git-2022.321.10303-e567d9c/htdoc/node_modules/vite/dist/node/chunks/dep-db16f19c.js:45662:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oui-app@ build: `vite build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oui-app@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lihh/.npm/_logs/2022-11-22T15_12_33_293Z-debug.log
make[2]: *** [../../oui.mk:50: /home/lihh/oui/lede/build_dir/target-x86_64_musl/oui-app-acl-git-2022.321.10303-e567d9c/.built] Error 1
make[2]: Leaving directory '/home/lihh/oui/lede/feeds/oui/applications/oui-app-acl'
time: package/feeds/oui/oui-app-acl/compile#0.59#0.08#0.61
    ERROR: package/feeds/oui/oui-app-acl failed to build.
make[1]: *** [package/Makefile:116: package/feeds/oui/oui-app-acl/compile] Error 1

**Comment by zhaojh329** [comment]
https://github.com/zhaojh329/oui/issues/202

**Comment by ligehhh** [comment]
重新拉取项目也试过了 node版本也换过

**Comment by ligehhh** [comment]
已解决

**Comment by RadioOperator** [comment]
怎么解决的呀。
