### ISSUE TITLE
web运行正常，用vscode运行npm run dev后报错

### ISSUE THREAD

**Issue by yunhai20082008** [zhaojh329/oui#222]
Environment: (put here arch, model, OpenWrt version)
- openwrt是官方master，x86，没有luci
- vscode是装在了win10 64位里
Description:
- openwrt里的oui，web运行的很好
- vscode报错，把oui-master或者oui-ui-core用工作目录的形式打开都是一样的报错
```
37 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS D:\oui-master\oui-ui-core\htdoc> npm run dev

> dev
> vite

failed to load config from D:\oui-master\oui-ui-core\htdoc\vite.config.js
error when starting dev server:
Error: EPERM: operation not permitted, symlink 'D:\oui-master\applications\oui-app-acl\htdoc' -> 'D:\oui-master\oui-ui-core\htdoc\src\applications\oui-app-acl\htdoc'
    at Object.symlinkSync (node:fs:1745:3)
    at D:\oui-master\oui-ui-core\htdoc\vite.config.js:73:25
    at Array.forEach (<anonymous>)
    at D:\oui-master\oui-ui-core\htdoc\vite.config.js:68:44
    at loadConfigFromFile (file:///D:/oui-master/oui-ui-core/htdoc/node_modules/vite/dist/node/chunks/dep-ca21228b.js:62225:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolveConfig (file:///D:/oui-master/oui-ui-core/htdoc/node_modules/vite/dist/node/chunks/dep-ca21228b.js:61843:28)
    at async createServer (file:///D:/oui-master/oui-ui-core/htdoc/node_modules/vite/dist/node/chunks/dep-ca21228b.js:61153:20)
    at async CAC.<anonymous> (file:///D:/oui-master/oui-ui-core/htdoc/node_modules/vite/dist/node/cli.js:734:24)
```

**Comment by yunhai20082008** [comment]
soloved
